### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maxemiliang** [maxemiliang/shot-benchmarker#1]
- [x] Run benchmark X amount of times
- [x] Store average + median
- [x] Print out what type of SHOT (gams/regular)
- [x] List all the separate benchmark runs in the benchmark results table (not comparison)
- For SHOT/Masters
  - [x] Gurobi + GAMS versions as inputs
  - [x] Write about how to add secrets.
